# Generated by Django 4.2.11 on 2024-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_power', models.BooleanField()),
                ('light', models.BooleanField()),
                ('heart', models.BooleanField()),
                ('gender', models.BooleanField()),
                ('sadness', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('temperature', models.BooleanField()),
                ('water', models.BooleanField()),
                ('tv', models.BooleanField()),
                ('weather', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
